#' Fit the Unrestricted Conditional Error Correction Model
#'
#' The classical half of the package: the unrestricted conditional error
#' correction model of Pesaran, Shin and Smith (2001),
#' \deqn{\Delta y_t = c_0 + c_1 t + \pi_y y_{t-1} + \pi_x' x_{t-1}
#'       + \sum_{i=1}^{p-1}\psi_{yi}\Delta y_{t-i}
#'       + \sum_{i=0}^{q-1}\psi_{xi}'\Delta x_{t-i} + \gamma' z_t + u_t,}
#' from which the speed of adjustment is \eqn{\alpha = -\pi_y} and the long-run
#' coefficients are \eqn{\theta = \pi_x/\alpha}.
#'
#' @param y Numeric vector: outcome in levels.
#' @param x Matrix or data frame of long-run forcing regressors in levels.
#' @param lags ARDL order \eqn{p}.
#' @param order ARDL order \eqn{q}.
#' @param case Deterministic case, an integer in 1:5. Cases 2 and 3 estimate the
#'   same model and differ only in whether the intercept is inside the tested
#'   null; the same holds for the trend in cases 4 and 5.
#' @param fixed Optional matrix of regressors entered contemporaneously and
#'   never lagged -- the \eqn{z_t} of the ARDL literature. They shift short-run
#'   dynamics but are excluded from the long-run relationship, which is what you
#'   want for a variable that predicts the outcome but cannot plausibly
#'   cointegrate with it.
#'
#' @return A list with the design matrix \code{X}, the response \code{dy},
#'   \code{coefficients}, \code{vcov}, \code{nobs} and the column names of the
#'   level terms.
#'
#' @examples
#' df <- passthrough_regime("1999-2007")
#' m <- conditional_ecm(df$cpi, cbind(neer = df$neer), lags = 4, case = 3)
#' m$nobs
#'
#' @references
#' Pesaran, M. H., Shin, Y. and Smith, R. J. (2001). Bounds testing approaches
#' to the analysis of level relationships. \emph{Journal of Applied
#' Econometrics}, 16(3), 289--326. \doi{10.1002/jae.616}
#' @export
conditional_ecm <- function(y, x, lags = 1L, order = 1L, case = 3L,
                            fixed = NULL) {
  .check_case(case)
  y <- as.numeric(y)
  x <- as.matrix(x)
  if (is.null(colnames(x))) colnames(x) <- paste0("x", seq_len(ncol(x)))
  lags <- as.integer(lags)
  order <- as.integer(order)
  n_all <- length(y)

  dy <- .diff1(y)
  dx <- apply(x, 2L, .diff1)
  dx <- matrix(dx, nrow = n_all, dimnames = list(NULL, colnames(x)))

  cols <- list()
  if (case != 1L) cols[["const"]] <- rep(1, n_all)
  if (case == 5L) cols[["trend"]] <- seq_len(n_all)

  ## Lagged levels: the terms the step-1 null restricts.
  level_names <- c("y.L1", paste0(colnames(x), ".L1"))
  cols[["y.L1"]] <- .lag1(y)
  for (j in seq_len(ncol(x))) cols[[paste0(colnames(x)[j], ".L1")]] <- .lag1(x[, j])

  ## Short-run dynamics.
  if (lags >= 2L) {
    for (i in seq_len(lags - 1L)) {
      cols[[paste0("D.y.L", i)]] <- c(rep(NA_real_, i), dy[seq_len(n_all - i)])
    }
  }
  for (j in seq_len(ncol(x))) {
    for (i in seq_len(order) - 1L) {
      nm <- if (i == 0L) paste0("D.", colnames(x)[j]) else paste0("D.", colnames(x)[j], ".L", i)
      cols[[nm]] <- if (i == 0L) dx[, j] else c(rep(NA_real_, i), dx[seq_len(n_all - i), j])
    }
  }
  if (!is.null(fixed)) {
    fixed <- as.matrix(fixed)
    if (is.null(colnames(fixed))) colnames(fixed) <- paste0("z", seq_len(ncol(fixed)))
    for (j in seq_len(ncol(fixed))) cols[[colnames(fixed)[j]]] <- fixed[, j]
  }

  X <- do.call(cbind, cols)
  colnames(X) <- names(cols)
  ok <- stats::complete.cases(cbind(dy, X))
  X <- X[ok, , drop = FALSE]
  yy <- dy[ok]

  fit <- stats::lm.fit(X, yy)
  b <- fit$coefficients
  nobs <- length(yy)
  dof <- nobs - ncol(X)
  s2 <- sum(fit$residuals^2) / dof
  V <- s2 * tryCatch(solve(crossprod(X)), error = function(e) MASS_ginv(crossprod(X)))
  dimnames(V) <- list(colnames(X), colnames(X))

  list(X = X, dy = yy, coefficients = b, vcov = V, nobs = nobs, dof = dof,
       level_names = level_names, case = as.integer(case),
       x_names = colnames(x), sigma2 = s2)
}

#' The Classical Bounds Test
#'
#' All three steps of the Pesaran, Shin and Smith procedure. Rejecting the joint
#' \eqn{F} null is not on its own evidence of a level relationship, because two
#' degenerate cases survive it, so the \eqn{t} test on the speed of adjustment
#' and the Wald test on the long-run coefficients are reported alongside.
#'
#' The bracket is generated by \code{\link{simulate_pss_bounds}} at the model's
#' own sample size, not read off a table calibrated at \eqn{T = 1000}.
#'
#' @inheritParams conditional_ecm
#' @param nsim Replications for the simulated bracket.
#' @param seed Seed for the bracket simulation.
#' @param levels Significance levels for the bracket.
#'
#' @return An object of class \code{"classical_bounds"} with the \eqn{F} and
#'   \eqn{t} statistics, the step-3 Wald statistic and its p-value, the speed of
#'   adjustment, the long-run coefficients and the simulated bracket.
#'
#' @examples
#' df <- passthrough_regime("1999-2007")
#' # Small nsim keeps this quick; raise it for anything you report.
#' cb <- classical_bounds_test(df$cpi, cbind(neer = df$neer), lags = 4,
#'                             nsim = 100, seed = 1)
#' cb
#'
#' @references
#' Pesaran, M. H., Shin, Y. and Smith, R. J. (2001). Bounds testing approaches
#' to the analysis of level relationships. \emph{Journal of Applied
#' Econometrics}, 16(3), 289--326. \doi{10.1002/jae.616}
#' @export
classical_bounds_test <- function(y, x, lags = 1L, order = 1L, case = 3L,
                                  fixed = NULL, nsim = 20000L, seed = 0,
                                  levels = DEFAULT_LEVELS) {
  m <- conditional_ecm(y, x, lags = lags, order = order, case = case, fixed = fixed)
  k <- length(m$x_names)
  b <- m$coefficients
  V <- m$vcov
  nms <- names(b)

  tested <- m$level_names
  if (case == 2L && "const" %in% nms) tested <- c("const", tested)
  if (case == 4L && "trend" %in% nms) tested <- c(tested, "trend")
  loc <- match(tested, nms)
  if (anyNA(loc)) stop("level terms missing from the fitted model")

  coef_t <- b[loc]
  Vt <- V[loc, loc, drop = FALSE]
  f_stat <- as.numeric(crossprod(coef_t, solve(Vt, coef_t))) / length(loc)

  pi_y <- unname(b["y.L1"])
  se_y <- sqrt(V["y.L1", "y.L1"])
  t_stat <- pi_y / se_y
  alpha <- -pi_y

  ## Step 3: theta = pi_x / alpha, with the delta method for its covariance.
  xl <- paste0(m$x_names, ".L1")
  pi_x <- unname(b[xl])
  theta <- pi_x / alpha
  J <- matrix(0, nrow = k, ncol = length(b))
  iy <- match("y.L1", nms)
  for (r in seq_len(k)) {
    J[r, match(xl[r], nms)] <- 1 / alpha
    J[r, iy] <- pi_x[r] / alpha^2
  }
  v_theta <- J %*% V %*% t(J)
  theta_wald <- as.numeric(crossprod(theta, solve(v_theta, theta)))
  theta_p <- stats::pchisq(theta_wald, df = k, lower.tail = FALSE)

  bounds <- simulate_pss_bounds(k = k, case = case, TT = m$nobs, nsim = nsim,
                                levels = levels, seed = seed)

  structure(list(f_stat = f_stat, t_stat = t_stat, theta_wald = theta_wald,
                 theta_pvalue = theta_p, k = k, case = as.integer(case),
                 nobs = m$nobs, alpha = alpha,
                 long_run = stats::setNames(theta, m$x_names),
                 bounds = bounds,
                 n_restrictions = length(loc)),
            class = "classical_bounds")
}

#' Print a Classical Bounds Test
#'
#' @param x A \code{"classical_bounds"} object from
#'   \code{\link{classical_bounds_test}}.
#' @param ... Ignored.
#' @return Invisibly, \code{x}.
#' @examples
#' df <- passthrough_regime("1999-2007")
#' print(classical_bounds_test(df$cpi, cbind(neer = df$neer), lags = 4,
#'                             nsim = 100, seed = 1))
#' @export
print.classical_bounds <- function(x, ...) {
  cat("Classical bounds test (Pesaran, Shin and Smith 2001)\n")
  cat(sprintf("H0: no level relationship          F = %.3f\n", x$f_stat))
  cat(sprintf("Case %d (%s)    t = %.3f\n", x$case,
              CASE_LABELS[[as.character(x$case)]], x$t_stat))
  cat(sprintf("k = %d forcing regressor(s), %d observations, %d restrictions\n\n",
              x$k, x$nobs, x$n_restrictions))
  cat(sprintf("simulated bounds (T = %d):\n", x$nobs))
  print(x$bounds, row.names = FALSE, digits = 4)
  cat(sprintf("\nstep 3  Wald(theta = 0) = %.3f  (chi2 p = %.4f)\n",
              x$theta_wald, x$theta_pvalue))
  cat(sprintf("speed of adjustment alpha = %.4f\n", x$alpha))
  invisible(x)
}

#' Mark a Statistic Against a Pair of Bounds
#'
#' Returns \code{"reject"} above the upper bound, \code{"inconclusive"} between
#' the two, and \code{"fail to reject"} below the lower bound. A single verdict
#' would hide the inconclusive region, which is the whole point of a bounds test.
#'
#' @param stat The statistic.
#' @param lower,upper The bracket.
#' @return A character string.
#' @examples
#' bounds_verdict(6.2, lower = 4.94, upper = 5.73)
#' bounds_verdict(5.2, lower = 4.94, upper = 5.73)
#' bounds_verdict(2.0, lower = 4.94, upper = 5.73)
#' @export
bounds_verdict <- function(stat, lower, upper) {
  if (!is.finite(stat)) return(NA_character_)
  if (stat > upper) return("reject")
  if (stat > lower) return("inconclusive")
  "fail to reject"
}
